---
- name: Apply CIS Benchmark security/compliance hardenning to the NEW RHEL 9 VM 
  hosts: all
  become: true
  become_method: sudo

  tasks: 
    - name: set password for ec2-user
      ansible.builtin.user:
        name: ec2-user
        password: redhat!23
