---
- name: Apply CIS Benchmark security/compliance hardenning to the NEW RHEL 9 VM 
  hosts: all
  become: true
  become_method: sudo
  tasks: 
    - name: set password for ec2-user
      ansible.builtin.user:
        name: ec2-user
        password: "{{ ec2_password|password_hash('sha512') }}"
    - name: Update clout-init generated sudoers
      ansible.builtin.blockinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          ec2-user ALL=(ALL)	ALL

    - name: Update authorised_keys
      ansible.builtin.blockinfile:
        path: /home/ec2-user/.ssh/authorized_keys
        marker: "# {mark} ANSIBLE MANAGED KEYS"
        block: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHifDabwcFZc9n2lXRU0PLKx32nwuCu+0UiQVxQo3r71 brosenbe EdDSA
